'use client';
import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { redirect } from 'next/navigation';

// Types for TypeScript
interface Requirement {
  key: string;
  title: string;
  description: string;
  required: boolean;
  category: string;
}

interface Document {
  id: string;
  requirementKey: string;
  filename: string;
  status: 'valid' | 'expired' | 'pending';
  expiryDate?: string;
}

interface Alert {
  id: string;
  message: string;
  type: 'warning' | 'info';
  requirementKey: string;
}

// Mock data for business types (replace with real data from /data/complianceRequirements)
const getBusinessTypes = () => ({
  takeaway: { subtypes: ['pizza', 'chinese', 'bubble_tea'] },
  cafe: { subtypes: ['coffee', 'bubble_tea'] },
});

export default function ComplianceHub() {
  const { data: session, status } = useSession();
  const [businessType, setBusinessType] = useState<string>('takeaway');
  const [subtype, setSubtype] = useState<string>('pizza');
  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [complianceScore, setComplianceScore] = useState<number>(0);
  const [loading, setLoading] = useState<boolean>(true);
  const [showAIChat, setShowAIChat] = useState<boolean>(false);
  const [aiQuestion, setAiQuestion] = useState<string>('');

  const businessTypes = getBusinessTypes();

  useEffect(() => {
    if (status === 'loading') return;
    if (!session || session.user?.role !== 'business') redirect('/login');
    loadComplianceData();
  }, [businessType, subtype, session, status]);

  const loadComplianceData = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/compliance?businessType=${businessType}&subtype=${subtype}`);
      
      if (response.ok) {
        const data = await response.json();
        setRequirements(data.requirements || []);
        setDocuments(data.documents || []);
        setAlerts(data.alerts || []);
        setComplianceScore(data.complianceScore || 0);
      } else {
        console.error('Failed to load compliance data');
      }
    } catch (error) {
      console.error('Error loading compliance data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDocumentUpload = async (requirementKey: string, file: File, expiryDate?: string) => {
    try {
      const formData = new FormData();
      formData.append('requirementKey', requirementKey);
      formData.append('file', file);
      if (expiryDate) formData.append('expiryDate', expiryDate);
      formData.append('businessType', businessType);
      formData.append('subtype', subtype);

      const response = await fetch('/api/compliance/documents', {
        method: 'POST',
        body: formData,
      });

      if (response.ok) {
        await loadComplianceData();
        return true;
      }
      return false;
    } catch (error) {
      console.error('Upload error:', error);
      return false;
    }
  };

  const handleDownloadTemplate = async (requirementKey: string) => {
    try {
      const response = await fetch(`/api/compliance/templates/${requirementKey}?businessType=${businessType}`);
      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${requirementKey}_template.docx`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      }
    } catch (error) {
      console.error('Download error:', error);
      // Fallback to a simple text file
      const templateContent = `Template for ${requirementKey}\n\nBusiness: ${businessType}\nGenerated by Aumvia Compliance Hub`;
      const blob = new Blob([templateContent], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${requirementKey}_template.txt`;
      a.click();
      window.URL.revokeObjectURL(url);
    }
  };

  const handleAskAI = (question: string) => {
    setAiQuestion(question);
    setShowAIChat(true);
  };

  const handleExportReport = async () => {
    try {
      const response = await fetch(`/api/compliance/export?businessType=${businessType}&subtype=${subtype}`);
      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `compliance-report-${businessType}-${new Date().toISOString().split('T')[0]}.pdf`;
        a.click();
        window.URL.revokeObjectURL(url);
      }
    } catch (error) {
      console.error('Export error:', error);
      alert('Export feature coming soon!');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-emerald-600 mx-auto mb-4"></div>
          <div className="text-gray-600">Loading your compliance hub...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-6">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Compliance Header (Simplified - Create component if needed) */}
        <div className="bg-white rounded-lg shadow p-6 mb-6">
          <h1 className="text-2xl font-bold text-gray-900">Compliance Hub</h1>
          <p className="text-gray-600">Compliance Score: {complianceScore}%</p>
          <div className="mt-4 flex space-x-4">
            <select value={businessType} onChange={(e) => setBusinessType(e.target.value)} className="border p-2 rounded">
              {Object.keys(businessTypes).map((type) => (
                <option key={type} value={type}>{type}</option>
              ))}
            </select>
            <select value={subtype} onChange={(e) => setSubtype(e.target.value)} className="border p-2 rounded">
              {businessTypes[businessType as keyof typeof businessTypes]?.subtypes.map((sub) => (
                <option key={sub} value={sub}>{sub}</option>
              ))}
            </select>
            <button onClick={handleExportReport} className="bg-blue-500 text-white px-4 py-2 rounded">Export Report</button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          <div className="lg:col-span-3">
            {/* Compliance Checklist (Simplified - Create component if needed) */}
            <div className="bg-white rounded-lg shadow p-6">
              <h2 className="text-xl font-bold mb-4">Compliance Checklist</h2>
              {requirements.map((req) => (
                <div key={req.key} id={`requirement-${req.key}`} className="mb-4 p-4 border rounded">
                  <h3 className="font-semibold">{req.title}</h3>
                  <p>{req.description}</p>
                  <button onClick={() => handleAskAI(`What do I need for ${req.title}?`)} className="text-blue-500 underline">Ask AI</button>
                  <button onClick={() => handleDownloadTemplate(req.key)} className="ml-4 text-green-500 underline">Download Template</button>
                  {/* Add upload logic here */}
                </div>
              ))}
            </div>
          </div>

          <div className="lg:col-span-1">
            {/* Compliance Sidebar (Simplified) */}
            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="font-bold mb-4">Alerts</h3>
              {alerts.map((alert) => (
                <div key={alert.id} className="mb-2 p-2 bg-yellow-100 rounded">
                  {alert.message}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* AI Chat Assistant (Placeholder - Integrate OpenAI) */}
        {showAIChat && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
            <div className="bg-white p-6 rounded-lg max-w-md">
              <h3 className="font-bold mb-4">AI Assistant</h3>
              <p>Question: {aiQuestion}</p>
              <p>Answer: [Integrate OpenAI API for real Q&A]</p>
              <button onClick={() => setShowAIChat(false)} className="mt-4 bg-red-500 text-white px-4 py-2 rounded">Close</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}